apiVersion: v1
kind: Secret
metadata:
    name: threadwise-secrets
    namespace: threadwise-prod
    labels:
        app: threadwise
type: Opaque
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:+PlISpLzXQh5IK4Ho+KIV+CACTJaLuIhtMo/x+kOwI+WLTgFoYWGkWa7QreJSrimc8pgkj/q541gVr3W3dLCHgPXlUbkhCyeg9t4wU2qh06XHjN+Cd1n+EaVSI3QqHNLaq2SxpeDkKZFd57EDq9xDXEhWw2zRK1asaJDW72wiK3/dxsZchi5XAYEO0ZfMS6sX1HUkm4WVYRVIJz2itYaT/ZNjYw=,iv:CXWQHB+uBLWSjQRGFPVsjG/7d+BOmV5beuZegyIEkU4=,tag:iLIs/ZqQ/3DwdSwLwZ0udw==,type:str]
    SLACK_BOT_TOKEN: ENC[AES256_GCM,data:4vDKPu8NTQwk+p1sKIRZ2hfV2+qoDFJZZ7+1hVoz2IP2E2iJdoFqQOtG/iJ3YjjgEsuiduVuxvx+,iv:jTl6c7isRRoyBzqqb/Anrb+STcEAFcsWadTpRic0yeU=,tag:Yt1kyDmtd9rYcOc2fdw+3A==,type:str]
    SLACK_CHANNEL_ID: ENC[AES256_GCM,data:cuL2huqXUuRWDfs=,iv:kBUBVr5UcfhyX9SXHlXguZTGH5J00E2Mc5EU/2tnVsg=,tag:lKIQxtJ5YTGUQTnH0xj03w==,type:str]
    LLM_API_KEY: ENC[AES256_GCM,data:CFxETcDNrP3I7r5FMmwwc9NNxVQkvWuqy4N5HKzzMiGZCYx5UVp7zkiesYI78G4agAMvFGjNfCB74eLfWphlb3RvDEVklcTI/Txm8OjaB6Cr0U+yUpPPPuVgiLy+Y57qrE14gtsrwtDn4nqr90lWWX3tdB9Cao5UITc7fTUpwigR8lkhieTSUgpB35NBhe7NYODkS2Piwg5Xtnwz1wZ26M7638s=,iv:M6jUm5MQTbbrugmHVnTi49yskNq4WkkDRKkR7ZJuOY0=,tag:knwnP1MPxevn/h+3wrXBTw==,type:str]
    JIRA_API_TOKEN: ENC[AES256_GCM,data:jOs24I4eXl2KbduRPCA1sLYY85C7EhZH/5vuhKWQ5jca03BkyHeT4pq39S4mP0PKnjcX4YhLKFdenYTTeTElkM2bDFAHE1IxukaRO4ooV/Zb8LFfJ/YnyJ2n0KkY7lxAwFFokMwCuaWm6ITjLNk8oMot3Dy35fKipMhRdJN1NxvpyqXT/kwL9PGXpSNgVc3cK/gEuF5WifSScks2vcjZ3oNnvfgwEx+uP2MxQuOveQ0L0NDxTDcG2cQCS4e8QCRA,iv:th3eRbgO5xySipgMbppN5kZtuoYUYcVJwpqrIKInnpY=,tag:Maxkwb3IcWKJirXQoOstQA==,type:str]
sops:
    age:
        - recipient: age1qx62w8zq4zgsaygqa5lhwh0w8vgy50suwj523wqqcfeuqa9ucvpqh5duq7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVzc3d0pCS2lFdXR6cklm
            SFBuM1hLWFZZajE4WVhnQU9SR2NyMjFRbHlBCmY2bFVkSGdZSVI2VGZNdnljRlR5
            U0RmTXBZS0hqVDA3QU5NRU95d3Q1YWMKLS0tIDhic1N1MUpiM0t3YXRXNkN0eFd6
            YjRoSjVMWmlwZlV2THdjVWRFNG9XM2sKEKsv3CGErDP1++lX3u+OoTP837D3MRz5
            8ahjFQWMEzeRYlzN3CyTsnI+RUphanGR/fcJXV0NiIjueIgxJuNBUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T04:56:57Z"
    mac: ENC[AES256_GCM,data:NiI/5PIYw2ubuQQ6H2Mkv2SIy5p4H0d9bivSC9Y1HfrLMQfy3ZMRJt4Q9jbjzYsdCm1iAfnLZ0iExVooSFHiybqk7A2/7Ah5ctEs6vZ7qGsueewvWs0odthJ0WOm+y+bY1GsjliWJWBNdacplW/cWBAxLAYalordeCQmk+6uvGc=,iv:NgIzi4L9yHse25ASDsNT4nOKhnUtnvJLdLZfBWrTCyU=,tag:PgStjCv5fFe4T42v21nRWg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
