apiVersion: v1
kind: Secret
metadata:
    name: threadwise-secrets
    namespace: threadwise-prod
    labels:
        app: threadwise
type: Opaque
stringData:
    slack-bot-token: ENC[AES256_GCM,data:kQAUVrN4zNKF2mD6U7AL/Fr6u+Od262QkrKOjF8=,iv:DgaYa2n0FyvrNI3iINLc1F7Fb9DJe3GGWTO4Q7K+4LU=,tag:FoiVTc1DsgbJ8JpjLInOmQ==,type:str]
    slack-channel-id: ENC[AES256_GCM,data:OurX+MSWQSHB8w==,iv:sw9G0aztEh4IyQbNuMJJo0rpQad56bEBSg1+UISMPQQ=,tag:n/0+HnZV4XnYgZHoAPGyOQ==,type:str]
    llm-api-key: ENC[AES256_GCM,data:1OHRih0X7BQAe39YGhuhX/sjgkulVDE=,iv:INN8BV1FO4BcDvbLUWSIXcuEts0FzE6rvT+FSU5L9KA=,tag:Pl1MT3UuS6aFV0Uc1R6QGA==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:ra1/4VAZtb+V3qQLl9e73uRW3BfnrGBNshiSauDQE604Uuk1UxuM+HH3LuhUEDlZTey5O/eWd3B23BTBsx7AGvBC3p/hJZlZcpfsM+TgVntZd/u/febtnS+4/sOyOyHsW7vVVlmlzPx+2wOtTpbQwQF6Ucta3Wkkd4xmx6eQoE64x/v53WUklP9Vot0zBrZGuIL6Jz0jy0N97t+icbBGnqo+pXM=,iv:XEc+XpenM+PyJYUsENpqGG9AiyHNFt0MY8zYn6itRag=,tag:J0JDMxkZVApySlSzplrARg==,type:str]
    SLACK_BOT_TOKEN: ENC[AES256_GCM,data:7uPK/M3zC7/CcfUZ7loVybxKPpmXn11jJtJ1fFAo1i3GbtOoOYts1F+WZBXWm/T/hIQ0PCLL45Ps,iv:7YsXFgIp6J+sgBQObTkDrIvt+bYrBhDeQkshTps8lvI=,tag:acYyJkmIZOOQ0DYE6UPtQQ==,type:str]
    SLACK_CHANNEL_ID: ENC[AES256_GCM,data:kwR4e720r+W1Xgs=,iv:jc6EdpnS4Ga50xF/RY1WaTcg4kdjjISG8u3892ZDzlQ=,tag:hWFHLB/ok80FttFElx9U3A==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:O7swu16F3FIhYso=,iv:+67VPZhX8mYNdY5n4/zRho32Oeue60LkxvDmsALiqeg=,tag:4SBchPyXJw/s3nOhTWajlg==,type:str]
    LLM_PROVIDER: ENC[AES256_GCM,data:hPogH8gH,iv:VbXOTKQcQBqUHsCYRXvphqesuOhWV0D3n0eOPWBJgjg=,tag:pWdlXyuAy8+rJh+gv8KQvg==,type:str]
    LLM_API_KEY: ENC[AES256_GCM,data:4MC80ITNIBL5lTLHtwOk8fIFf6bjEpEX4mTBWo57geQj12xdXJk/wU1GNrAdINBbzuZGSVuPPzQItGoql4GfzxSMI55I/r/K/jfsRTVmzmRckX8MWBQy/LjcDomvcbt1+jiD5JWsAxWd67+0u1ixaS0gIKGvXDDuWtmhKR6nY95vlkCsA5ui/RcDKUtTBInZ+JCCZtg0Ig+PY9ssmJgzTGbxWD8=,iv:Um9XifAYySXlWhoSeFV9AqKq2ZkvoxBJ3rAP66ijBA4=,tag:CG9UZG/qEYs3gaRskl9VWw==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:MKVb0iuVhgcB3DSBBQYQOGylB8r7G6/rlrCvlmrwhO5GL7sHghy6GK2VTIwbmHriq+zVmtdNw3CYGx0+Bqyt30xooc1YcxEijg==,iv:h6z3fd0KEF/I+mzTdotrlDV6oi3CvQ/G3OCdEFu3h/s=,tag:tiMkyt2IL/SVGT9pA1N1hw==,type:str]
    LLM_MODEL: ENC[AES256_GCM,data:VZKGNO0AmxeinXM=,iv:lSWi67J73rmlObEezzAmL8KgrrdwmnG2CuzwvQG9/xg=,tag:zPAfUilmIezZY9YXkAxaZQ==,type:str]
    JIRA_BASE_URL: ENC[AES256_GCM,data:u7VDneug8Yc2VkQcC90ga2TepJWvV36mpdxgazdSYaFlillB,iv:4vt6IY+Z5bbk+wQAWHvZtpSsxTEQGk87VxEM2Lmly9M=,tag:4lc59bLu6hppYTOMPpS6fg==,type:str]
    JIRA_EMAIL: ENC[AES256_GCM,data:pJQfgZ10ihyyJzZPGSkKZpGE3Sk=,iv:yDxHT72mTeYXJfm/dYPAGMHxT+eIOJYtm+/kX0yzN1w=,tag:R20M0BwoY38pgfY0l0ENYA==,type:str]
    JIRA_API_TOKEN: ENC[AES256_GCM,data:FFUHogBPnt9Sy2ayO244wnWxEcpoxdP61pWtEoHaRJZmhqQYQHtoH84qPXfDC+O+D1sZOCgkDfmA0FOZ+KyklRhZhrCSa2ALsAF8gJ9NF4hVMiMC6Gi2aA8iriPnq8Jp9DL91N/t40xTHzDLdEkAik959YkH1PfAQiWaH4yh8I6nNJ3q8SBX+A/ayMuH30YNwyeCZEDpKhuUgjfOWLZcu37kvPTi8vF6KqqI06ADlY6xYTudahTVlHDsyIfuuu7Y,iv:hadhtKi+iwNG/qqbkis8pTC7V1ca7Wz14BBE3/WVvf0=,tag:vBQDVn7+jPgPxhwfNzb9lQ==,type:str]
    JIRA_PROJECT_KEY: ENC[AES256_GCM,data:E08JgfE=,iv:Na/bSF4znIZWc6bk5e0j2F5yJAhMq4aCcPDn8yST6rU=,tag:ypGVWwt1D3Qv6CJDztc2Pw==,type:str]
    JIRA_BOARD_ID: ENC[AES256_GCM,data:4Q==,iv:3gx6nhllJXXD0BUpc4B/6wUFCFWjCyQ2Xx04LVehzaE=,tag:osSUo7FwYJhgQPy/6Dx8Dw==,type:str]
sops:
    age:
        - recipient: age1qx62w8zq4zgsaygqa5lhwh0w8vgy50suwj523wqqcfeuqa9ucvpqh5duq7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjd1ZIRy9EWEZnQVdvQkJm
            cEVzV05XYzk1ZEF5aFJuTWRHcnByNGNHWkJNCk1EUm9BR1JvQWkxRDZNYVpxS3Rk
            SHMrVC9hNEtQZEc3WU9pbWUrN3kzRE0KLS0tIGJNajh3QUMxbmxRQ1pJWDhod2pU
            MXdkZnNtbk85aUl5K0xleUs5ekxOZFkK9tuKh3yLnGAujA13lt/Fwn72RbbmQwJB
            eVr6vei1gkSsklSZAf4f/pbyyieJAdIGWCTf8LyDcc7/UBLEZW/XMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T04:43:07Z"
    mac: ENC[AES256_GCM,data:Rix6Jhmcm7EQ3MCBUJgZQBS9ZU6GBefUU5Xk61T9xKQ6kvsTk0lIcdrnaOJwQBfaUs84rcZUyDWN3vrPE6QvXjYXqh/7WHT+mJvRfHAq0yfO8AHPSS/pUXEi0LaOw3q6ZWf6loElz2Y+hxkfQiEYUWVzjS4wIqWBkfEIOMvLBmA=,iv:ahjQmqNvD6ZtcFxLJRMC1DwZan7+FnSaxyiIsmvY0Jc=,tag:+2BoYWKFsP9WXvvd/VKTsw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
